### ISSUE TITLE
The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by HorexC** [cnzx219/NewEBuy#1]
是不是又被删除了啊。。。
admindeMacBook-Pro:NewEBuy admin$ git clone https://bitbucket.org/liruqi/newebuy.git
Cloning into 'newebuy'...
remote: Counting objects: 7073, done.
remote: Compressing objects: 100% (5221/5221), done.
error: RPC failed; result=18, HTTP code = 200B | 4.00 KiB/s  
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
admindeMacBook-Pro:NewEBuy admin$

**Comment by CyberTianzun** [comment]
还在，也许是网络问题

https://bitbucket.org/liruqi/newebuy

**Comment by CyberTianzun** [comment]
remote: Counting objects: 7073, done.

你的log里边很明显数据都检查完毕了啊，多试几次吧，毕竟 bitbucket 是外国服务器，网络不稳定很正常
